version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mikhaildb
      POSTGRES_USER: mikhail
      POSTGRES_PASSWORD: 2275450q
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: mikhaildb
      DB_USER: mikhail
      DB_PASSWORD: 2275450q
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    command: ["python", "main.py"]

volumes:
  db_data:
