version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mikhaildb
      POSTGRES_USER: mikhail
      POSTGRES_PASSWORD: 2275450q
    ports:
      - "5433:5432"
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mikhaildb
      DB_USER: mikhail
      DB_PASSWORD: 2275450q
    depends_on:
      - db
    command: python main.py
